/// Flutter icons TabbedView
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
import 'package:flutter/widgets.dart';

/// [TabbedView] icons
class TabbedViewIcons {
  TabbedViewIcons._();

  static const _kFontFam = 'TabbedView';
  static const String? _kFontPkg = 'tabbed_view';

  static const IconData close =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
